language: scala

scala:
  - 2.10.5
  - 2.11.8
  - 2.12.0

env:
  - JDK=oraclejdk8
  - JDK=openjdk6

before_script:
  - jdk_switcher use $JDK

matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.0
      env: JDK=openjdk6

# Use the container-based infrastructure.
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
